repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
  - repo: https://github.com/asottile/blacken-docs
    rev: master
    hooks:
      - id: blacken-docs
  - repo: https://github.com/psf/black
    rev: master
    hooks:
      - id: black
