from typing import Optional

import structlog
from google.protobuf.empty_pb2 import Empty

# generated by protoc
from vision_filter.proto.filter_visualizer_grpc import FilterVisualizerBase
from vision_filter.proto.ssl.field.geometry_pb2 import GeometryFieldSize

from .visualizer import Visualizer


class FilterVisualizerService(FilterVisualizerBase):
    def __init__(self, visualizer: Visualizer):
        self._log = structlog.get_logger()
        self._visualizer = visualizer

    async def SetFieldGeometry(self, stream):
        request: GeometryFieldSize = await stream.recv_message()
        self._log.debug("SetFieldGeometry", request=request)
        await self._visualizer.set_field_geometry(request)
        await stream.send_message(Empty())

    async def GetFieldGeometry(self, stream):
        request: Empty = await stream.recv_message()
        self._log.debug(f"GetFieldGeometry", request=request)
        await stream.send_message(await self._visualizer.get_field_geometry())
